spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fillTheVoidDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop
       ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8